### ISSUE TITLE
Failed to run the script(s)

### ISSUE THREAD

**Issue by arnikz** [CSuperlei/DeepSV#3]
Hi,

I've tried to run the script(s) as described in the `README.md` but got stuck on the way. Please see my suggestions in [this](https://github.com/CSuperlei/DeepSV/pull/4) PR. The command-line interface does not include e.g. `-h|--help` (nor input VCF file). 

```$ python Deletion_Image_Source/Generate_Deletion_Image.py -h
Traceback (most recent call last):
  File "Deletion_Image_Source/Generate_Deletion_Image.py", line 78, in <module>
    main()
  File "Deletion_Image_Source/Generate_Deletion_Image.py", line 50, in main
    vcf_file = file.get_vcf_file(vcf_path,'deletion')   
  File "/home/arnikz/Downloads/DeepSV/Deletion_Image_Source/FILE_CLASS.py", line 3, in get_vcf_file
    deletion_pos = open(vcf_path,'r')
FileNotFoundError: [Errno 2] No such file or directory: 'your file path'
```
Could you add a working example including a small dataset? Thank you.

**Comment by FEIFEIEIAr** [comment]
For your problem, you should change 'your file path' to your own path, like '/home/.../your_vcf.vcf', in line 78 of Generate_Deletion_Image.py.
However, I read some codes of DeepSV, I found a lot of mistakes, which means that you should change plenty of codes then you can really run it.

**Comment by chycheng2015** [comment]
I also found that these scripts contain many mistakes, and are not consistent with what are described  in the paper published on BMC bioinformatics
